exports.default = {
  vibraLeft1: "VIBRA LEFT 1",
  vibraRight1: "VIBRA RIGHT 1",
  vibraLeft2: "VIBRA LEFT 2",
  vibraRight2: "VIBRA RIGHT 2",
  vibraLeft3: "VIBRA LEFT 3",
  vibraRight3: "VIBRA RIGHT 3",
  vibraLeft4: "VIBRA LEFT 4",
  vibraRight4: "VIBRA RIGHT 4",
  vibraLeft5: "VIBRA LEFT 5",
  vibraRight5: "VIBRA RIGHT 5",
  vibraLeft6: "VIBRA LEFT 6",
  vibraRight6: "VIBRA RIGHT 6",
  vibraLeft7: "VIBRA LEFT 7",
  vibraRight7: "VIBRA RIGHT 7",
  vibraLeft8: "VIBRA LEFT 8",
  vibraRight8: "VIBRA RIGHT 8",
  vibraLeft9: "VIBRA LEFT 9",
  vibraRight9: "VIBRA RIGHT 9",
  vibraLeft10: "VIBRA LEFT 10",
  vibraRight10: "VIBRA RIGHT 10",
  vibraLeft11: "VIBRA LEFT 11",
  vibraRight11: "VIBRA RIGHT 11",
  cymbalL: "CYMBAL L",
  cymbalR: "CYMBAL R",
  kickL: "KICK L",
  kickR: "KICK R",
  snareL: "SNARE L",
  snareR: "SNARE R",
  hihatL: "HIHAT L",
  hihatR: "HIHAT R",
  bassL1: "BASS L 1",
  bassR1: "BASS R 1",
  bassL2: "BASS L 2",
  bassR2: "BASS R 2",
  bassL3: "BASS L 3",
  bassR3: "BASS R 3",
  bassL4: "BASS L 4",
  bassR4: "BASS R 4"
}